import { FC } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/decorators/ThemeProvider';
import Navbar from '@/containers/navbar/Navbar';
import { Separator } from '@/components/ui/separator';
import { Toaster } from '@/components/ui/toaster';
import Footer from '@/containers/footer/Footer';
import ReactQueryProvider from '@/decorators/ReactQueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: FC<Readonly<Props>> = ({ children }) => {
  return (
    <ThemeProvider defaultTheme="dark">
      <html lang="en">
        <ReactQueryProvider>
          <body className={`${inter.className}`}>
            <Toaster />

            {children}
          </body>
        </ReactQueryProvider>
      </html>
    </ThemeProvider>
  );
};

export default RootLayout;
