import { FC } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { ThemeProvider } from '@/decorators/ThemeProvider';
import Navbar from '@/containers/navbar/Navbar';
import { Separator } from '@/components/ui/separator';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const StoreLayout: FC<Readonly<Props>> = ({ children }) => {
  return (
    <ThemeProvider defaultTheme="light">
      <html lang="en">
        <body className={inter.className}>
          <header className="bg-background sticky top-0 z-50">
            <Navbar />
            <Separator />
          </header>

          {children}
        </body>
      </html>
    </ThemeProvider>
  );
};

export default StoreLayout;
