import { FC } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { ThemeProvider } from '@/decorators/ThemeProvider';
import Navbar from '@/containers/navbar/Navbar';
import { Separator } from '@/components/ui/separator';
import Footer from '@/containers/footer/Footer';
import ReactQueryProvider from '@/decorators/ReactQueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const StoreLayout: FC<Readonly<Props>> = ({ children }) => {
  return (
    <ThemeProvider defaultTheme="dark">
      <ReactQueryProvider>
        <html lang="en">
          <body className={`${inter.className} flex flex-col min-h-screen`}>
            <header className="bg-background sticky top-0 z-50">
              <Navbar />
              <Separator />
            </header>

            <main className="flex-1">{children}</main>

            <Footer />
          </body>
        </html>
      </ReactQueryProvider>
    </ThemeProvider>
  );
};

export default StoreLayout;
